### ISSUE TITLE
setting workplane after construction is being ignored 

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#312] opened 2020-09-29 09:18 UTC
I came across this bug while making images for the docs

This is not on the short term list of things to fix but will become more relevant when we want to export reactor images using the ToroidalFieldCoilTripleArc, it might also be an issue upstream instead of in the paramak

However it appears the svg export breaks when 3 or more magnets are used

```
import paramak

component = paramak.ToroidalFieldCoilTripleArc(
    R1=80,
    h=200,
    radii=(70, 100),
    coverages=(60, 60),
    thickness=30,
    distance=30,
    number_of_coils=1,
    workplane='XY'
)
component.export_svg('1_magnets.svg')
```

![Screenshot from 2020-09-29 10-17-12](https://user-images.githubusercontent.com/8583900/94539349-04b28100-023d-11eb-822b-5b2d8c9b4fe9.png)

This appears to not work
```
component = paramak.ToroidalFieldCoilTripleArc(
    R1=80,
    h=200,
    radii=(70, 100),
    coverages=(60, 60),
    thickness=30,
    distance=30,
    number_of_coils=3,
    component.workplane = "XY"
)
component.export_svg('3_magnets.svg')
```

![Screenshot from 2020-09-29 10-17-39](https://user-images.githubusercontent.com/8583900/94539356-0714db00-023d-11eb-99a4-91215b6610c8.png)

**Comment by billingsley-john** [comment] 2020-09-29 09:51
I think this is linked to #308

**Comment by RemDelaporteMathurin** [comment] 2020-11-02 08:22
@Shimwell i think the title of this issue is incorrect. The workplane _can_ be set after construction (see below).

```python
component = paramak.ToroidalFieldCoilTripleArc(
    R1=80,
    h=200,
    radii=(70, 100),
    coverages=(60, 60),
    thickness=30,
    distance=30,
    number_of_coils=3,
)
```
produces : 
![image](https://user-images.githubusercontent.com/40028739/97844713-c7ce2400-1ceb-11eb-9b13-fc35a5a2a86b.png)

Which is the expected behaviour.

```python
component = paramak.ToroidalFieldCoilTripleArc(
    R1=80,
    h=200,
    radii=(70, 100),
    coverages=(60, 60),
    thickness=30,
    distance=30,
    number_of_coils=3,
)
component.workplane = "XY"
```

produces 
![image](https://user-images.githubusercontent.com/40028739/97844795-ee8c5a80-1ceb-11eb-925d-4f3e40bd0b86.png)

Which also is the expected since the rotation axis in Shape.rotate_solid() is independent on workplane.
Regardless of the workplane, the rotation axis will always be the Z axis : 
https://github.com/ukaea/paramak/blob/10552f1b89820dd0f7a08e4a126834877e3106b4/paramak/shape.py#L514-L517

One way to fix this would be to make the rotation axis depend on the workplane.
I think it can even be a parameter that, by default, makes the rotation axis orthogonal to the workplane. It can be useful to have flexibility here.

What do you think @Shimwell @billingsley-john  ?

**Comment by Shimwell** [comment] 2020-11-02 14:09
this is perfect

**Comment by RemDelaporteMathurin** [comment] 2020-11-11 11:21
@Shimwell shall we close this ?

**Comment by Shimwell** [comment] 2020-11-11 16:49
Might be related to this one as well #462

**Closed** 2020-11-17 14:50 UTC
Labels: bug
