### ISSUE TITLE
Hollow ToroidalFieldCoilPrincetonD shapes

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#272] opened 2020-09-21 20:49 UTC
ToroidalFieldCoilPrincetonD sometimes retuns with a hollow shell instead of a solid shape

![Screenshot from 2020-09-21 21-47-55](https://user-images.githubusercontent.com/8583900/93819895-40a18100-fc54-11ea-9632-c9f47fdfeda4.png)

code used to make the above example error

```
    import paramak
    outer_tf = paramak.ToroidalFieldCoilPrincetonD(
        R1=400,
        R2=1500,
        thickness=100,
        distance=100,
        number_of_coils=number_of_toroidal_field_coils
    )
```

**Comment by RemDelaporteMathurin** [comment] 2020-11-17 15:04
I'm not able to reproduce this in develop, perhaps this was fixed elsewhere... shall we close this ?

**Closed** 2020-11-23 16:32 UTC
Labels: bug
